version: "3"

services:
  postgres:
    image: postgres16:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hackportal
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - hackportal-develop-network

  hackportal-backend:
    build: .
    restart: always
    environment:
    # Server Settings 
      - SERVER_ADDR=8080
      - SERVER_SHUTDOWN_TIMEOUT=5
      - SERVER_READ_TIMEOUT=5
    # Database Connection Settings
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hackportal
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Asia/Tokyo
      - DB_CONNECT_TIMEOUT=10
      - DB_CONNECT_WAIT_TIME=10
      - DB_CONNECT_ATTEMPTS=3
      - DB_CONNECT_BLOCKS=false
      - DB_CLOSE_TIMEOUT=5
    # NewRelic Settings
      - NEW_RELIC_LICENSE_KEY=
      - NEW_RELIC_APP_NAME=
      - NEW_RELIC_CODE_LEVEL_METRICS_ENABLED=
      - NEW_RELIC_LABELS=
      - NEW_RELIC_LOG_LEVEL=
      - NEW_RELIC_LOG_ENABLED=
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - hackportal-develop-network
networks:
  hackportal-develop-network:
    external:
      true