version: "3"

services:
  postgres:
    build: 
      context: .docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hack_portal
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: .docker/migrate/Dockerfile
    restart: "no"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hack_portal
    depends_on:
      - redis
      - postgres

  redis:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ".docker/redis/data:/data"

  hackportal-backend:
    build:
      context: .
      dockerfile: .docker/app/local.Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - migrate