version: "3"

services:
  postgres:
    build: 
      context: .docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hack_portal
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data

  # hackportal-backend:
  #   build:
  #     context: .docker/app
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   networks:
  #     - hackportal-develop-network
