apiVersion: v1
kind: Namespace
metadata:
  name: app-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-deploy
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLavels:
      app: app-test
  templates:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: harbor.seaffood.com/hackhack/hackhack-backend@sha256:615d0539ec3615c2244e9e4b940a6950c0200750b4d81266be1f76fc1ffeaa04
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-svc
  namespace: app-test
  labels:
    app: app-test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: app-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-ingress
  namespace: app-test
spec:
  rules:
  - host: "seaffoo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-svc
            port:
              number: 80
    