apiVersion: v1
kind: Service
metadata:
  name: hackhack-backend
spec:
  type: NodePort
  selector:
    app: hackhack-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 31000