basePath: /api/v1
definitions:
  api.BookmarkResponse:
    properties:
      description:
        type: string
      expired:
        type: string
      hackathon_id:
        type: integer
      icon:
        type: string
      link:
        type: string
      name:
        type: string
      start_date:
        type: string
      term:
        type: integer
    type: object
  api.CreateAccountRequestBody:
    properties:
      explanatory_text:
        type: string
      frameworks:
        items:
          type: integer
        type: array
      icon:
        type: string
      locate_id:
        type: integer
      password:
        type: string
      show_locate:
        type: boolean
      show_rate:
        type: boolean
      tech_tags:
        items:
          type: integer
        type: array
      user_id:
        type: string
      username:
        type: string
    required:
    - locate_id
    - show_locate
    - show_rate
    - user_id
    - username
    type: object
  api.CreateAccountResponses:
    properties:
      explanatory_text:
        type: string
      frameworks:
        items:
          $ref: '#/definitions/db.Frameworks'
        type: array
      icon:
        type: string
      locate:
        type: string
      rate:
        type: integer
      show_locate:
        type: boolean
      show_rate:
        type: boolean
      tech_tags:
        items:
          $ref: '#/definitions/db.TechTags'
        type: array
      user_id:
        type: string
      username:
        type: string
    type: object
  api.CreateBookmarkRequestBody:
    properties:
      hackathon_id:
        type: integer
      user_id:
        type: string
    type: object
  api.CreateFollowRequestBody:
    properties:
      to_user_id:
        type: string
    required:
    - to_user_id
    type: object
  api.DeleteResponse:
    properties:
      result:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.GetAccountResponses:
    properties:
      email:
        type: string
      explanatory_text:
        type: string
      frameworks:
        items:
          $ref: '#/definitions/db.Frameworks'
        type: array
      icon:
        type: string
      locate:
        type: string
      rate:
        type: integer
      show_locate:
        type: boolean
      show_rate:
        type: boolean
      tech_tags:
        items:
          $ref: '#/definitions/db.TechTags'
        type: array
      user_id:
        type: string
      username:
        type: string
    type: object
  api.UpdateAccountRequestBody:
    properties:
      explanatory_text:
        type: string
      hashed_password:
        type: string
      locate_id:
        type: integer
      rate:
        type: integer
      show_locate:
        type: boolean
      show_rate:
        type: boolean
      username:
        type: string
    type: object
  api.UpdateAccountResponse:
    properties:
      created_at:
        type: string
      explanatory_text:
        type: string
      hashed_password:
        type: string
      icon:
        type: string
      locate:
        type: string
      rate:
        type: integer
      show_locate:
        type: boolean
      show_rate:
        type: boolean
      username:
        type: string
    type: object
  db.Follows:
    properties:
      create_at:
        type: string
      from_user_id:
        type: string
      to_user_id:
        type: string
    type: object
  db.Frameworks:
    properties:
      framework:
        type: string
      framework_id:
        type: integer
      tech_tag_id:
        type: integer
    type: object
  db.TechTags:
    properties:
      language:
        type: string
      tech_tag_id:
        type: integer
    type: object
host: https://seaffood.com
info:
  contact:
    email: oogiriminister@gmail.com
    name: murasame
    url: https://twitter.com/fresh_salmon256
  description: HackPortal Backend API serice
  license:
    name: No-license
    url: No-license
  termsOfService: https://seaffood.com/api
  title: Hack Hack Backend API
  version: "1.0"
paths:
  /acccounts/{from_user_id}/follow:
    delete:
      description: Remove follow
      parameters:
      - description: remove Follow Request path
        in: path
        name: from_user_id
        required: true
        type: string
      - description: remove Follow Request Body
        in: body
        name: RemoveFollowRequestQueries
        required: true
        schema:
          $ref: '#/definitions/api.CreateFollowRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: succsss response
          schema:
            items:
              $ref: '#/definitions/db.Follows'
            type: array
        "400":
          description: error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Remove follow
      tags:
      - AccountsFollow
    post:
      description: Create Follow
      parameters:
      - description: create Follow Request path
        in: path
        name: from_user_id
        required: true
        type: string
      - description: create Follow Request Body
        in: body
        name: CreateFollowRequestBody
        required: true
        schema:
          $ref: '#/definitions/api.CreateFollowRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: succsss response
          schema:
            items:
              $ref: '#/definitions/db.Follows'
            type: array
        "400":
          description: error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create Follow
      tags:
      - AccountsFollow
  /accounts:
    post:
      description: Create new account
      parameters:
      - description: Create Account Request Body
        in: body
        name: CreateAccountRequestBody
        required: true
        schema:
          $ref: '#/definitions/api.CreateAccountRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: create succsss response
          schema:
            $ref: '#/definitions/api.CreateAccountResponses'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create new account
      tags:
      - Accounts
  /accounts/{user_id}:
    delete:
      description: Only you can delete your account (logical delete)
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: delete succsss response
          schema:
            $ref: '#/definitions/api.DeleteResponse'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Remove Account
      tags:
      - Accounts
    get:
      description: Get Any Account
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get success response
          schema:
            $ref: '#/definitions/api.GetAccountResponses'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get account
      tags:
      - Accounts
    put:
      description: Update process when it matches the person
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: Update Account Request Body
        in: body
        name: UpdateAccountRequestBody
        required: true
        schema:
          $ref: '#/definitions/api.UpdateAccountRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Update succsss response
          schema:
            $ref: '#/definitions/api.UpdateAccountResponse'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Update Account
      tags:
      - Accounts
  /bookmarks:
    post:
      description: Create new bookmark
      parameters:
      - description: New Bookmark Request Body
        in: body
        name: CreateBookmarkRequestBody
        required: true
        schema:
          $ref: '#/definitions/api.CreateBookmarkRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: create succsss response
          schema:
            $ref: '#/definitions/api.BookmarkResponse'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create new bookmark
      tags:
      - Bookmark
  /bookmarks/{hackathon_id}:
    delete:
      description: delete bookmark
      parameters:
      - description: Delete Bookmark Request Body
        in: path
        name: hackathon_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: delete succsss response
          schema:
            $ref: '#/definitions/api.BookmarkResponse'
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: delete bookmark
      tags:
      - Bookmark
    get:
      description: Get bookmark
      parameters:
      - description: Delete Bookmark Request Body
        in: formData
        name: ListBookmarkRequestQueries
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: delete succsss response
          schema:
            items:
              $ref: '#/definitions/api.BookmarkResponse'
            type: array
        "400":
          description: bad request response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: server error response
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get my bookmark
      tags:
      - Bookmark
swagger: "2.0"
