basePath: /v1
definitions:
  input.HackathonCreate:
    properties:
      expired:
        type: string
      link:
        type: string
      name:
        type: string
      start_date:
        type: string
      status_tags:
        type: string
      term:
        type: integer
    type: object
  output.CreateHackathon:
    properties:
      message:
        type: string
    type: object
host: api.seafood-dev.com
info:
  contact:
    email: oogiriminister@gmail.com
    name: murasame29
    url: https://twitter.com/fresh_salmon256
  description: Hack Hack Backend API serice
  license:
    name: No-license
  termsOfService: https://api.seafood-dev.com
  title: Hack Hack Backend API
  version: 0.1.0
paths:
  /hackathons:
    post:
      description: Register a hackathon from given parameters
      parameters:
      - description: create hackathon Request Body
        in: body
        name: CreateHackathonRequest
        required: true
        schema:
          $ref: '#/definitions/input.HackathonCreate'
      produces:
      - application/json
      responses:
        "200":
          description: success response
          schema:
            $ref: '#/definitions/output.CreateHackathon'
        "400":
          description: error response
        "500":
          description: error response
      summary: Create Hackathon
      tags:
      - Hackathon
swagger: "2.0"
