name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - shell: bash
        run: |
          rm app.env && touch app.env
          echo "${{ secrets.APP_ENV }}" >> app.env
          cat app.env

      - name: Translate secrets of base64 into json
        env:
          JSON_DECODE: ${{ secrets.CREDENTIALS_JSON }}

        run: |
          echo -n $JSON_DECODE | base64 --decode > ./serviceAccount.json

      - name: Build, tag, and push image to harbor
        env:
          REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
          USERNAME: ${{ secrets.HARBOR_USERNAME }}
          PASSWORD: ${{ secrets.HARBOR_PASSWORD }} 

      - uses: docker/login-action@v1
        with:
          registry: $REGISTRY
          username: $REGISTRY
          password: $PASSWORD

      - uses: actions/checkout@v3
      - name: BuildAndPushImageOnHarbor
        run: |
          docker build -t $REGISTRY/hackhack/hackhack-backend:${{ github.sha }}
          docker push $REGISTRY/hackhack/hackhack-backend:${{ github.sha }}
