name: Deploy to production

on:
  push:
    branches: [ ft/cicd ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: harbor.seaffood.com
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t harbor.seaffood.com/chaturmail/chaturmail-backend:${{ github.run_number }}
        docker push harbor.seaffood.com/chaturmail/chaturmail-backend:${{ github.run_number }}