name: Deploy to production

on:
  push:
    branches: [ ft/cicd ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: loginDocker
      run: |
        docker login -u ${{ secrets.HARBOR_USERNAME  }} -p ${{ secrets.HARBOR_PASSWORD }} ${{ secrets.HARBOR_REGISTRY }}
    
    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t harbor.seaffood.com/chaturmail/chaturmail-backend:${{ github.run_number }}
        docker push harbor.seaffood.com/chaturmail/chaturmail-backend:${{ github.run_number }}

    - name: logoutDocker
      run : |
        docker logout ${{ secrets.HARBOR_REGISTRY }}