name: Deploy to Staging

on:
  push:
    branches: [ develop ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - shell: bash
      run: |
        rm app.env && touch app.env
        echo "${{ secrets.STAGE_APP_ENV }}" >> app.env
        cat app.env

    - name: Translate secrets of base64 into json
      env:
        JSON_DECODE: ${{ secrets.CREDENTIALS_JSON }}

      run: |
        echo -n $JSON_DECODE | base64 --decode > ./serviceAccount.json

    - uses: docker/login-action@v1
      with:
        registry: ${{ secrets.HARBOR_REGISTRY  }}
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t ${{ secrets.HARBOR_REGISTRY  }}/hackhack/hackhack-backend:${{ github.run_number }}
        docker push ${{ secrets.HARBOR_REGISTRY  }}/hackhack/hackhack-backend:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: Hack-Hack-geek-Vol6/k8s-config
          ref: master
          path: configs
          
    
      - name: Change manifest
        run: |
          cd configs/config/manifest/stage
          yq -i '.spec.template.spec.containers[0].image = "${{ secrets.HARBOR_REGISTRY  }}/hackhack/hackhack-backend:${{ github.run_number }}"' 'deployment.yaml'
      
      - name: Create release pr
        run: gh pr create -B "master" -t "Develop" -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
