name: test

on:
  pull_request:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version@1.21.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: install dependencies
        run: |
          go mod tidy

      - name: Run postgres16-latest
        run: |
          docker run --name postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=hackportal -d postgres:16

      - name: Run go test
        run: make test